package com.github.liuche51.easyTask.dto.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduleDto.proto

public final class ScheduleDto {
  private ScheduleDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ScheduleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string classPath = 2;
    /**
     * <code>required string classPath = 2;</code>
     */
    boolean hasClassPath();
    /**
     * <code>required string classPath = 2;</code>
     */
    String getClassPath();
    /**
     * <code>required string classPath = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassPathBytes();

    // required int64 executeTime = 3;
    /**
     * <code>required int64 executeTime = 3;</code>
     */
    boolean hasExecuteTime();
    /**
     * <code>required int64 executeTime = 3;</code>
     */
    long getExecuteTime();

    // required string taskType = 4;
    /**
     * <code>required string taskType = 4;</code>
     */
    boolean hasTaskType();
    /**
     * <code>required string taskType = 4;</code>
     */
    String getTaskType();
    /**
     * <code>required string taskType = 4;</code>
     */
    com.google.protobuf.ByteString
        getTaskTypeBytes();

    // optional int64 period = 5;
    /**
     * <code>optional int64 period = 5;</code>
     */
    boolean hasPeriod();
    /**
     * <code>optional int64 period = 5;</code>
     */
    long getPeriod();

    // required string unit = 6;
    /**
     * <code>required string unit = 6;</code>
     */
    boolean hasUnit();
    /**
     * <code>required string unit = 6;</code>
     */
    String getUnit();
    /**
     * <code>required string unit = 6;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    // optional string param = 7;
    /**
     * <code>optional string param = 7;</code>
     */
    boolean hasParam();
    /**
     * <code>optional string param = 7;</code>
     */
    String getParam();
    /**
     * <code>optional string param = 7;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();

    // optional string backup = 8;
    /**
     * <code>optional string backup = 8;</code>
     */
    boolean hasBackup();
    /**
     * <code>optional string backup = 8;</code>
     */
    String getBackup();
    /**
     * <code>optional string backup = 8;</code>
     */
    com.google.protobuf.ByteString
        getBackupBytes();

    // optional string source = 9;
    /**
     * <code>optional string source = 9;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 9;</code>
     */
    String getSource();
    /**
     * <code>optional string source = 9;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();
  }
  /**
   * Protobuf type {@code Schedule}
   */
  public static final class Schedule extends
      com.google.protobuf.GeneratedMessage
      implements ScheduleOrBuilder {
    // Use Schedule.newBuilder() to construct.
    private Schedule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Schedule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Schedule defaultInstance;
    public static Schedule getDefaultInstance() {
      return defaultInstance;
    }

    public Schedule getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Schedule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              classPath_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              executeTime_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              taskType_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              period_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              unit_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              param_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              backup_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              source_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduleDto.internal_static_Schedule_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduleDto.internal_static_Schedule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Schedule.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Schedule> PARSER =
        new com.google.protobuf.AbstractParser<Schedule>() {
      public Schedule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Schedule(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Schedule> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string classPath = 2;
    public static final int CLASSPATH_FIELD_NUMBER = 2;
    private Object classPath_;
    /**
     * <code>required string classPath = 2;</code>
     */
    public boolean hasClassPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string classPath = 2;</code>
     */
    public String getClassPath() {
      Object ref = classPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          classPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string classPath = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassPathBytes() {
      Object ref = classPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        classPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 executeTime = 3;
    public static final int EXECUTETIME_FIELD_NUMBER = 3;
    private long executeTime_;
    /**
     * <code>required int64 executeTime = 3;</code>
     */
    public boolean hasExecuteTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 executeTime = 3;</code>
     */
    public long getExecuteTime() {
      return executeTime_;
    }

    // required string taskType = 4;
    public static final int TASKTYPE_FIELD_NUMBER = 4;
    private Object taskType_;
    /**
     * <code>required string taskType = 4;</code>
     */
    public boolean hasTaskType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string taskType = 4;</code>
     */
    public String getTaskType() {
      Object ref = taskType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTypeBytes() {
      Object ref = taskType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 period = 5;
    public static final int PERIOD_FIELD_NUMBER = 5;
    private long period_;
    /**
     * <code>optional int64 period = 5;</code>
     */
    public boolean hasPeriod() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 period = 5;</code>
     */
    public long getPeriod() {
      return period_;
    }

    // required string unit = 6;
    public static final int UNIT_FIELD_NUMBER = 6;
    private Object unit_;
    /**
     * <code>required string unit = 6;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string unit = 6;</code>
     */
    public String getUnit() {
      Object ref = unit_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string unit = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      Object ref = unit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string param = 7;
    public static final int PARAM_FIELD_NUMBER = 7;
    private Object param_;
    /**
     * <code>optional string param = 7;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string param = 7;</code>
     */
    public String getParam() {
      Object ref = param_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string param = 7;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      Object ref = param_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string backup = 8;
    public static final int BACKUP_FIELD_NUMBER = 8;
    private Object backup_;
    /**
     * <code>optional string backup = 8;</code>
     */
    public boolean hasBackup() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string backup = 8;</code>
     */
    public String getBackup() {
      Object ref = backup_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backup_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string backup = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBackupBytes() {
      Object ref = backup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        backup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string source = 9;
    public static final int SOURCE_FIELD_NUMBER = 9;
    private Object source_;
    /**
     * <code>optional string source = 9;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string source = 9;</code>
     */
    public String getSource() {
      Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      classPath_ = "";
      executeTime_ = 0L;
      taskType_ = "";
      period_ = 0L;
      unit_ = "";
      param_ = "";
      backup_ = "";
      source_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClassPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExecuteTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUnit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClassPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, executeTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTaskTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, period_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUnitBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getParamBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getBackupBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSourceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClassPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, executeTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTaskTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, period_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUnitBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getParamBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getBackupBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSourceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Schedule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Schedule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Schedule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Schedule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Schedule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Schedule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Schedule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Schedule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Schedule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Schedule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Schedule prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Schedule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ScheduleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduleDto.internal_static_Schedule_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduleDto.internal_static_Schedule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Schedule.class, Builder.class);
      }

      // Construct using ScheduleDto.Schedule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        classPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        executeTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        taskType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        period_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        unit_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        backup_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduleDto.internal_static_Schedule_descriptor;
      }

      public Schedule getDefaultInstanceForType() {
        return Schedule.getDefaultInstance();
      }

      public Schedule build() {
        Schedule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Schedule buildPartial() {
        Schedule result = new Schedule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.classPath_ = classPath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.executeTime_ = executeTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskType_ = taskType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.period_ = period_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.backup_ = backup_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Schedule) {
          return mergeFrom((Schedule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Schedule other) {
        if (other == Schedule.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasClassPath()) {
          bitField0_ |= 0x00000002;
          classPath_ = other.classPath_;
          onChanged();
        }
        if (other.hasExecuteTime()) {
          setExecuteTime(other.getExecuteTime());
        }
        if (other.hasTaskType()) {
          bitField0_ |= 0x00000008;
          taskType_ = other.taskType_;
          onChanged();
        }
        if (other.hasPeriod()) {
          setPeriod(other.getPeriod());
        }
        if (other.hasUnit()) {
          bitField0_ |= 0x00000020;
          unit_ = other.unit_;
          onChanged();
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000040;
          param_ = other.param_;
          onChanged();
        }
        if (other.hasBackup()) {
          bitField0_ |= 0x00000080;
          backup_ = other.backup_;
          onChanged();
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000100;
          source_ = other.source_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasClassPath()) {
          
          return false;
        }
        if (!hasExecuteTime()) {
          
          return false;
        }
        if (!hasTaskType()) {
          
          return false;
        }
        if (!hasUnit()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Schedule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Schedule) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string classPath = 2;
      private Object classPath_ = "";
      /**
       * <code>required string classPath = 2;</code>
       */
      public boolean hasClassPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string classPath = 2;</code>
       */
      public String getClassPath() {
        Object ref = classPath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          classPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string classPath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassPathBytes() {
        Object ref = classPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          classPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string classPath = 2;</code>
       */
      public Builder setClassPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        classPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string classPath = 2;</code>
       */
      public Builder clearClassPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        classPath_ = getDefaultInstance().getClassPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string classPath = 2;</code>
       */
      public Builder setClassPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        classPath_ = value;
        onChanged();
        return this;
      }

      // required int64 executeTime = 3;
      private long executeTime_ ;
      /**
       * <code>required int64 executeTime = 3;</code>
       */
      public boolean hasExecuteTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 executeTime = 3;</code>
       */
      public long getExecuteTime() {
        return executeTime_;
      }
      /**
       * <code>required int64 executeTime = 3;</code>
       */
      public Builder setExecuteTime(long value) {
        bitField0_ |= 0x00000004;
        executeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 executeTime = 3;</code>
       */
      public Builder clearExecuteTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        executeTime_ = 0L;
        onChanged();
        return this;
      }

      // required string taskType = 4;
      private Object taskType_ = "";
      /**
       * <code>required string taskType = 4;</code>
       */
      public boolean hasTaskType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public String getTaskType() {
        Object ref = taskType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          taskType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTypeBytes() {
        Object ref = taskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder setTaskType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder clearTaskType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskType_ = getDefaultInstance().getTaskType();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder setTaskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskType_ = value;
        onChanged();
        return this;
      }

      // optional int64 period = 5;
      private long period_ ;
      /**
       * <code>optional int64 period = 5;</code>
       */
      public boolean hasPeriod() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 period = 5;</code>
       */
      public long getPeriod() {
        return period_;
      }
      /**
       * <code>optional int64 period = 5;</code>
       */
      public Builder setPeriod(long value) {
        bitField0_ |= 0x00000010;
        period_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 period = 5;</code>
       */
      public Builder clearPeriod() {
        bitField0_ = (bitField0_ & ~0x00000010);
        period_ = 0L;
        onChanged();
        return this;
      }

      // required string unit = 6;
      private Object unit_ = "";
      /**
       * <code>required string unit = 6;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string unit = 6;</code>
       */
      public String getUnit() {
        Object ref = unit_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string unit = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string unit = 6;</code>
       */
      public Builder setUnit(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 6;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000020);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 6;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        unit_ = value;
        onChanged();
        return this;
      }

      // optional string param = 7;
      private Object param_ = "";
      /**
       * <code>optional string param = 7;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string param = 7;</code>
       */
      public String getParam() {
        Object ref = param_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          param_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string param = 7;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string param = 7;</code>
       */
      public Builder setParam(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 7;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000040);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 7;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        param_ = value;
        onChanged();
        return this;
      }

      // optional string backup = 8;
      private Object backup_ = "";
      /**
       * <code>optional string backup = 8;</code>
       */
      public boolean hasBackup() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string backup = 8;</code>
       */
      public String getBackup() {
        Object ref = backup_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          backup_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string backup = 8;</code>
       */
      public com.google.protobuf.ByteString
          getBackupBytes() {
        Object ref = backup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          backup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string backup = 8;</code>
       */
      public Builder setBackup(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        backup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string backup = 8;</code>
       */
      public Builder clearBackup() {
        bitField0_ = (bitField0_ & ~0x00000080);
        backup_ = getDefaultInstance().getBackup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string backup = 8;</code>
       */
      public Builder setBackupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        backup_ = value;
        onChanged();
        return this;
      }

      // optional string source = 9;
      private Object source_ = "";
      /**
       * <code>optional string source = 9;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public String getSource() {
        Object ref = source_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder setSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000100);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Schedule)
    }

    static {
      defaultInstance = new Schedule(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Schedule)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Schedule_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Schedule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ScheduleDto.proto\"\235\001\n\010Schedule\022\n\n\002id\030\001" +
      " \002(\t\022\021\n\tclassPath\030\002 \002(\t\022\023\n\013executeTime\030\003" +
      " \002(\003\022\020\n\010taskType\030\004 \002(\t\022\016\n\006period\030\005 \001(\003\022\014" +
      "\n\004unit\030\006 \002(\t\022\r\n\005param\030\007 \001(\t\022\016\n\006backup\030\010 " +
      "\001(\t\022\016\n\006source\030\t \001(\tB\rB\013ScheduleDto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Schedule_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Schedule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Schedule_descriptor,
              new String[] { "Id", "ClassPath", "ExecuteTime", "TaskType", "Period", "Unit", "Param", "Backup", "Source", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
